import {
    Activity,
    AlertCircle,
    AlertTriangle,
    AlignJustify,
    Anchor,
    Award,
    Bell,
    Book,
    BookOpen,
    Briefcase,
    Calendar,
    Camera,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clock,
    Code,
    Compass,
    Database,
    Download,
    Edit,
    ExternalLink,
    Eye,
    EyeOff,
    FileText,
    Flag,
    Folder,
    Gift,
    Globe,
    GraduationCap,
    Heart,
    Home,
    Image as ImageIcon,
    Info,
    Layout,
    Link,
    Lock,
    Mail,
    Map,
    MapPin,
    MessageCircle,
    MessageSquare,
    Monitor,
    Music,
    Paperclip,
    PenTool,
    Phone,
    PieChart,
    Play,
    Plus,
    School,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    Star,
    Target,
    Trash2,
    TrendingUp,
    Upload,
    User,
    UserCheck,
    UserPlus,
    Users,
    Video,
    Wifi
} from 'lucide-react';

// Registry ikon yang bisa dipilih oleh pengguna.
// Hanya ikon di dalam daftar ini yang akan di-bundle oleh Vite untuk Icon Picker.
export const PRESET_ICONS = {
    Activity, AlertCircle, AlertTriangle, AlignJustify, Anchor, Award,
    Bell, Book, BookOpen, Briefcase, Calendar, Camera, Check, CheckCircle,
    ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, Code,
    Compass, Database, Download, Edit, ExternalLink, Eye, EyeOff, FileText,
    Flag, Folder, Gift, Globe, GraduationCap, Heart, Home, ImageIcon, Info,
    Layout, Link, Lock, Mail, Map, MapPin, MessageCircle, MessageSquare,
    Monitor, Music, Paperclip, PenTool, Phone, PieChart, Play, Plus,
    School, Search, Send, Settings, Share2, Shield, Star, Target,
    Trash2, TrendingUp, Upload, User, UserCheck, UserPlus, Users, Video, Wifi
};

export type PresetIconName = keyof typeof PRESET_ICONS;
